version: "3.9"
name: simplebank-dev
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"
    volumes:
      - simplebank-dev:/var/lib/postgresql/data

volumes:
  simplebank-dev:
